/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.11/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
    id("com.vanniktech.maven.publish") version "0.34.0"
}

val artifactId = "io.github.ishan-karmakar.wpiformatter"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

gradlePlugin {
    plugins {
        create("wpiformatter") {
            id = artifactId
            implementationClass = "io.github.ishankarmakar.wpiformatter.WpiformatterPlugin"
        }
    }
}

tasks.named<Test>("test") {
    // Use JUnit Jupiter for unit tests.
    useJUnitPlatform()
}

mavenPublishing {
    publishToMavenCentral(automaticRelease = true)
    signAllPublications()

    coordinates(artifactId, "wpiformatter", "0.0.2")

    pom {
        name = "Wpiformatter"
        description = "A Gradle plugin to format FRC C++ projects with wpiformat"
        url = "https://github.com/ishan-karmakar/wpiformatter"
        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "http://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }

        developers {
            developer {
                id = "ishank"
                name = "Ishan Karmakar"
                url = "https://github.com/ishan-karmakar"
            }
        }
        scm {
            url = "https://github.com/ishan-karmakar/wpiformatter"
            connection = "scm:git:git://github.com/ishan-karmakar/wpiformatter"
            developerConnection = "scm:git:ssh://git@github.com/ishan-karmakar/wpiformatter"
        }
    }
}
