/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.11/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
    id("com.vanniktech.maven.publish") version "0.35.0"
}

val artifactId = "io.github.ishan-karmakar.wpiformatter"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter("6.0.1")
        }

        val functionalTest by registering(JvmTestSuite::class) {
            useJUnitJupiter("6.0.1")
            dependencies {
                implementation(project())
            }

            targets {
                all {
                    testTask.configure { shouldRunAfter(test) }
                }
            }
        }
    }
}

gradlePlugin {
    val wpiformatter by plugins.creating {
        id = artifactId
        implementationClass = "io.github.ishankarmakar.wpiformatter.WpiformatterPlugin"
    }

    testSourceSet(sourceSets["functionalTest"])
}

tasks.named("check") { dependsOn(tasks.named("functionalTest")) }

mavenPublishing {
    publishToMavenCentral(automaticRelease = true)
    signAllPublications()

    coordinates(artifactId, "wpiformatter", "1.0.1")

    pom {
        name = "Wpiformatter"
        description = "A Gradle plugin to format FRC C++ projects with wpiformat"
        inceptionYear = "2025"
        url = "https://github.com/ishan-karmakar/wpiformatter"
        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "http://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }

        developers {
            developer {
                id = "ishank"
                name = "Ishan Karmakar"
                url = "https://github.com/ishan-karmakar"
            }
        }
        scm {
            url = "https://github.com/ishan-karmakar/wpiformatter"
            connection = "scm:git:git://github.com/ishan-karmakar/wpiformatter"
            developerConnection = "scm:git:ssh://git@github.com/ishan-karmakar/wpiformatter"
        }
    }
}
