/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.ishankarmakar.wpiformatter;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'org.example.greeting' plugin.
 */
class WpiformatterPluginTest {
    @Test
    void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("io.github.ishan-karmakar.wpiformatter");

        assertNotNull(project.getExtensions().findByName("wpiformatter"));
        assertNotNull(project.getTasks().findByName("format"));
        assertNotNull(project.getTasks().findByName("lint"));
    }
}
